Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bucket-goodies

The diffrent commands used for today's lecture
  aws cloudformation create-stack --stack-name my-bucket-goodies --template-body file://S3-bucket.yaml
  aws cloudformation describe-stacks --stack-name my-bucket-goodies
  aws cloudformation delete-stack --stack-name my-bucket-goodies